### ISSUE TITLE
Move constructor and Move assignment cannot pass

### ISSUE THREAD

**Issue by zouzy5137** [PKUFlyingPig/CS106L#2]
Greetings! I tried to copy your Move constructor and Move assignment codes but they cannot pass the test program. Could you please reexamine those codes at your convenience?  Thank you so much.

**Comment by zouzy5137** [comment]
They're in the assignment-3 Hash-Map.

**Comment by turnaround5954** [comment]
> Greetings! I tried to copy your Move constructor and Move assignment codes but they cannot pass the test program. Could you please reexamine those codes at your convenience? Thank you so much.

check line 1620 in file tests.cpp, change temp to copy: 
VERIFY_TRUE(check_map_equal(new_assign, temp), __LINE__);   ->  VERIFY_TRUE(check_map_equal(new_assign, copy), __LINE__);

**Comment by zouzy5137** [comment]
> > Greetings! I tried to copy your Move constructor and Move assignment codes but they cannot pass the test program. Could you please reexamine those codes at your convenience? Thank you so much.
> 
> check line 1620 in file tests.cpp, change temp to copy: VERIFY_TRUE(check_map_equal(new_assign, temp), **LINE**); -> VERIFY_TRUE(check_map_equal(new_assign, copy), **LINE**);
Thank you so much!🥰 By the way, how did you find the solution? That's cool!🧐

**Comment by turnaround5954** [comment]
1. find the code corresponding to the failed test, read it carefully, you will find it will return false even when you implement the right thing.
2. compare the test code with code published here, then you will find the solution. ^_^
